#!/bin/sh

########## Variables
files="\
	.bashrc \
	.bash_profile \
	.profile \
	.gitconfig \
	.vimrc \
	.vim \
	.i3 \
	.julia/config/startup.jl \
	.Xresources \
	Xcolorschemes \
	.urxvt \
	.scripts \
	.tmux.conf \
	.inputrc \
	.config/zathura/zathurarc \
	"

df_dir=~/dotfiles
bak_dir=~/dotfiles_bak
home_dir=~

########## Functions
rmdir_rel()
{
	workdir="$(pwd -P)"
	cd "$2" || return 1
	reltarget=$(realpath --relative-to="$2" "$1")
	[ "$reltarget" != "." ]	&& rmdir -p "$reltarget"
	cd "$workdir" || return 1
}

backup_old_dotfile()
{
	dotfile=$home_dir/$1
	bakpath=$bak_dir/$1
	if [ -e "$dotfile" ] || [ -L "$dotfile" ]; then
		mkdir -p "${bakpath%/*}"
		mv "$dotfile" "$bakpath"
		rmdir_rel "${dotfile%/*}" "$home_dir"
		return 0
	fi
	return 1
}

symlink_dotfile()
{
	linkname=$home_dir/$1
	target=$df_dir/$1
	mkdir -p "${linkname%/*}"
	ln -s "$target" "$linkname"
	return 0
}

backup_all()
{
	echo "Backing up existing dotfiles:"
	for file in $files; do
		backup_old_dotfile "$file" && echo "  $file"
	done
}

symlink_all()
{
	echo "Creating symlinks to:"
	for file in $files; do
		symlink_dotfile "$file" && echo "  $file"
	done
}

########## Run installer
backup_all
symlink_all
