#!/bin/sh

########## Variables
files="\
	.bashrc \
	.bash_profile \
	.profile \
	.gitconfig \
	.vimrc \
	.vim \
	.i3 \
	.julia/config \
	.Xresources \
	.Xcolorschemes \
	.urxvt \
	.scripts \
	.tmux.conf \
	.inputrc \
	.config/zathura \
	"

df_dir=~/dotfiles
bak_dir=~/dotfiles_bak
home_dir=~

########## Functions
backup_backups()
{
	if [ -d "$bak_dir" ]; then
		old_bak_dir=${bak_dir}/${bak_dir##*/}
		echo "Backing up previous backups to: ${old_bak_dir}"
		mv "$bak_dir" tmp_bak_dir
		mkdir -p "$old_bak_dir"
		mv -T tmp_bak_dir "$old_bak_dir"
	fi
}

backup_old_dotfile()
{
	dotfile=$home_dir/$1
	bakpath=$bak_dir/$1
	if [ -e "$dotfile" ]; then
		mkdir -p "${bakpath%/*}"
		mv "$dotfile" "$bakpath"
		return 0
	fi
	return 1
}

symlink_dotfile()
{
	linkname=$home_dir/$1
	target=$df_dir/$1
	mkdir -p "${linkname%/*}"
	ln -s "$target" "$linkname"
	return 0
}

backup_all()
{
	cd "$home_dir"
	echo "Backing up existing dotfiles:"
	for file in $files; do
		backup_old_dotfile "$file" && echo "  $file"
	done
}

symlink_all()
{
	cd "$home_dir"
	echo "Creating symlinks to:"
	for file in $files; do
		symlink_dotfile "$file" && echo "  $file"
	done
}

########## Run installer
backup_backups
backup_all
symlink_all
