#!/bin/bash

# Setup monitor layout
xrandr --output HDMI-1 --primary --pos 0x0 --output HDMI-3 --pos -1200x0 --rotate left

# Set mouse speed
xset m 1 0
xinput --set-prop 'Primax Kensington Eagle Trackball' 'libinput Accel Profile Enabled' 0 1
xinput --set-prop 'Logitech USB-PS/2 Optical Mouse' 'libinput Accel Profile Enabled' 0 1
xinput --set-prop 'Logitech USB-PS/2 Optical Mouse' 'Coordinate Transformation Matrix' 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0

