#!/bin/sh
# Based on: https://faq.i3wm.org/question/150/how-to-launch-a-terminal-from-here/?answer=152#post-id-152

ID=$(xdpyinfo 2>/dev/null | sed -n 's/focus.\+window\s\+\(0x[0-9a-e]\+\).*/\1/p')
PID=$(xprop -id "${ID}" 2>/dev/null | sed -n 's/.*PID.*\s\([0-9]\+\)$/\1/p')
PID_LEAF=$(pstree -lpA "${PID}" 2>/dev/null | sed -n '1s/.*(\([0-9]\+\))$/\1/p')

DIR="$HOME"
[ -e "/proc/${PID_LEAF}/cwd" ] || DIR=$(readlink "/proc/${PID_LEAF}/cwd")


cd "${DIR}" && $TERMINAL
