#!/bin/bash

# tex file comes first
file="$1"
name=${file%.tex} #remove file extension
shift

# Default build command
cmd="pdflatex"
# cmdopt="-shell-escape -synctex=1 -interaction=nonstopmode"
cmdopt="-shell-escape -synctex=1"

# View command
[ "$OSTYPE" == "msys" ] &&	viewcmd="SumatraPDF.exe"
[ "$OSTYPE" == "linux-gnu" ] && viewcmd="zathura"

# Parse rest of arguments
while getopts ":bvnlx" opt; do
	case ${opt} in
		b) bib="set" ;;
		v) view="set" ;;
		n) nobuild="set" ;;
		l) cmd="lualatex" ;;
		x) cmd="xelatex" ;;
		\?) echo "Invalid option. Remember: options must come last." 1>&2 ; exit ;;
	esac
done

# Build
if ! [ -n "$nobuild" ]; then
	${cmd} "${cmdopt}" "${name}.tex"
	if [ -n "$bib" ]; then
		bibtex "${name}.aux"
		${cmd} "${cmdopt}" "${name}.tex"
		${cmd} "${cmdopt}" "${name}.tex"
	fi
fi

# View pdf
[ -n "$view" ] && ${viewcmd} "${name}.pdf" &
