#!/bin/sh

# Script to disable/re-enable all tmux bindings, including the prefixed ones.
# The script removs the prefix key and sets the 'disable-bindings' key-table as
# root table. The 'disable-bindings'-table should be empty apart. However, you
# can add a binding to it that unlocks tmux. The scripts also changes the colors
# of tmux to indicate it being locked.

tmux_nested_lock()
{
	tmux \
		set prefix None \;\
		set key-table disable-bindings \;\
		set status-left-style fg=colour0,bg=colour3 \;\
		set status-style fg=colour0,bg=colour3 \;\
		set status-right-style fg=colour0,bg=colour3 \;\
		set window-status-current-style fg=colour3,bg=colour0 \;\
		set pane-border-style fg=colour3,bg=colour0 \;\
		set pane-active-border-style fg=colour3,bg=colour0
}

tmux_nested_unlock()
{
	tmux \
		set -u prefix \;\
		set -u key-table \;\
		set -u status-left-style \;\
		set -u status-style \;\
		set -u status-right-style \;\
		set -u window-status-current-style \;\
		set -u pane-border-style \;\
		set -u pane-active-border-style
}

# Parse arguments
[ -z "$1" ] && echo "Options: -l to lock tmux, -t to unlock." && exit
while :; do
    case $1 in
        -l)
			tmux_nested_lock ; exit ;;
        -u)
			tmux_nested_unlock ; exit ;;
        *)
			echo "Invalid option." 1>&2 ; exit ;;
    esac
    shift
done
