#!/bin/sh

# Options
case $1 in
	'') ;;
	ignore) opt="-ignorearchives" ;;
	*) echo "Invalid option." 1>&2 ; exit ;;
esac

# run unison on all profiles
for file in ~/.unison/*.prf; do
	prf_file=${file##*/}
	profile=${prf_file%.prf}
	echo "Running: unison $profile $opt"
	unison $profile $opt
	echo ""
done

# force a flush of files (mainly unison archives) to drive, wsl2 might otherwise
# forget to do so if rebooted directly after
sync
