#!/bin/sh

wc -c ~/.unison/fp*
wc -c ~/.unison/ar*

for file in ~/.unison/*.prf; do
	prf_file=${file##*/}
	profile=${prf_file%.prf}
	echo "Running: unison $profile"
	unison "$profile"
	echo ""
done

wc -c ~/.unison/fp*
wc -c ~/.unison/ar*
